# Generated by Django 3.0.4 on 2020-09-27 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gifts_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemed',
            name='redeemed_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
