# Generated by Django 3.0.4 on 2020-09-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200927_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='is_satisfied',
        ),
    ]
